import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import QueryMoviesSeriesProvider from "@/plugins/QueryMoviesProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const montse = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montse.className}>
        <Navbar />
        <QueryMoviesSeriesProvider>{children}</QueryMoviesSeriesProvider>
        <Footer />
      </body>
    </html>
  );
}
